server:
  port: 8100

spring:
  #因为本微服务不需要数据库，所以排除数据库自动配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300

feign:
  client:
    config:
      default:
        connectTimeout: 300
        readTimeout: 5000