server:
  port: 8100

spring:
  zipkin:
    base-url: http://linux104:9411/
    sender:
      type: web
  #因为本微服务不需要数据库，所以排除数据库自动配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration