server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://linux104:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://linux104:9411
    sender:
      type: web
minio:
  base:
    url: "http://linux104:9000"
    accessKey: "JDFAA2PO0XGEHQG1WRHF"
    secretKey: "+SNq3Sxk6kDuGV1fTwgSE5yoEDhdYL1DVCp+i7OK"